---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mosquitto
  namespace: default
spec:
  encryptedData:
    passwd: AgDN7OmPnVgFo4mTLlHFSCezzbg/QGWPo0pOza5z0rBTbC9yIeIRYlEuDdADjpKZm95STuXViG+0JodoI0XRQSgcLuMfiNeLlEyy3eXDJpvUZHPUgdYs3GjObGuZCQfF0m4ufL0W9MyXmek5efxqkLAlpd6ThaV2hpC4kl+KPC6Pq+vraP10DO2Rt86za7UxPKuKyJteu97hucgLIfeo1H0uFnyOxfF2Ad4qTNY3jfsHZDvthru0AdMjckENcY6FAnjY+lVTABbWVATYMu+UGNFmekCGKIswq31bILwUHkh4CZKgUhbHzaR/iGj4llPX+QWQpZ0jCAPQbAcgrwEdQqjaRKT1+TF/9PSEmcAdenNdiHDx0Xw7lPZFxMfdcGinJMj+0LBeImr/BhxZOmBpOk/6VBYXqvXzj6zVAkBF/upDll1XXsIEf8cXHaRtMXHq4bOtZ5DmsC4iqb8U8BfvT5z84pJEiZznpJinai82wxCr4qmO0vmicWtPA3XG4eZ9++MnVTDUvFM38RCGbFocwEVB+WG2jN5bbNE7edJdHlXkekUbywz22Vc79wnpfgLlpNf+GOv/a3UoZFCPLJ2ubl0MBs38yUIObmiR6t67eK2gKzGaKIel8zt6CSJ0KqCJUHM7EgXQUGyqpyZn9b3SNbYDS2+G0SlICJb1zL8KeHW+F3Py2YTyosQA4cdoobXspZqxmT2tjiJ/x1IdX77AuiXHbaYYVcQBL3xaevNPawQ6Q534cGKnB6/YgvdaZyS5wNXJnyVU41CCFVSqujZWmwzC1SZla79LU6GaRhrY9nKleAopZkQar2Q+8sulcrg7nHT8KQI0LLWLyiQNSem6/rQ=
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: mosquitto
        meta.helm.sh/release-namespace: default
      creationTimestamp: null
      labels:
        app.kubernetes.io/managed-by: Helm
      name: mosquitto
      namespace: default
    type: Opaque
